apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: test-env-subnet3
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "4"
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1c
    cidrBlock: 10.0.3.0/24
    vpcIdRef:
      name: test-env
    mapPublicIPOnLaunch: false
  providerConfigRef:
    name: localstack
